services:
  go:
    build: .
    ports:
      - "8282:8282"
    environment:
      - REDIS_ADDR=db:6379

  db:
    image: redis:8.6-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data: