{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-pod-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: url-shortener
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: url-shortener
      app.kubernetes.io/instance: {{ .Release.Name }}
  podMetricsEndpoints:
  - port: api
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
{{- end }}