apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: url-shortener
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.auth.password | default "" | quote }}
  {{- if not .Values.postgresql.enabled }}
  CONNECTION_STRING: {{ .Values.database.connectionString | quote }}
  {{- end }}