apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ .Release.Name }}-stateful-set
    namespace: {{ .Release.Namespace }}
    labels:
        app.kubernetes.io/name: url-shortener
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ .Release.Name }}-headless
  podManagementPolicy: Parallel
  replicas: {{ .Values.replicas | default 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: url-shortener
      app.kubernetes.io/instance: {{ .Release.Name }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: url-shortener
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault

      initContainers:
      {{- if .Values.postgresql.enabled }}
      - name: wait-postgres
        image: busybox:1.37
        command: ['sh', '-c', 
          'until nc -z -w 2 {{ .Release.Name }}-postgres-rw 5432; do echo waiting for postgres; sleep 2; done'
        ]
      {{- end }}

      {{- if .Values.redis.enabled }}
      - name: wait-redis
        image: busybox:1.37
        command: ['sh', '-c', 
          'until nc -z -w 2 {{ .Release.Name }}-redis 6379; do echo waiting for redis; sleep 2; done'
        ]
      {{- end }}
      containers:
      - name: shortener
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        env:
        - name: APP_NAME
          value: {{ .Release.Name }}
        - name: ENVIRONMENT
          value: {{ .Values.environment | default "test" | quote }}
        - name: PORT
          value: {{ .Values.port | default "8080" | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.logLevel | default "info" | quote }}
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        - name: WORKERS_COUNT
          value: {{ .Values.workersCount | default "5" | quote}}
        - name: CHAN_BUFFER
          value: {{ .Values.chanBuffer | default "1000" | quote}}
        - name: APP_SHUTDOWN_TIMEOUT
          value: {{ .Values.shutdownTimeout | default "5s" | quote}}
        - name: HTTP_READ_TIMEOUT
          value: {{ .Values.server.readTimeout | default "5s" | quote }}
        - name: HTTP_WRITE_TIMEOUT
          value: {{ .Values.server.writeTimeout | default "10s" | quote }}
        - name: SERVER_SHUTDOWN_TIMEOUT
          value: {{ .Values.server.shutdownTimeout | default "3s" | quote }}
        - name: ENABLE_METRICS
          value: {{ .Values.metrics.enabled | default false | quote }}
        
        - name: REDIS_ADDRS
          {{- if and .Values.redis.enabled .Values.redis.sentinel.enabled }}
          value: "{{ .Release.Name }}-redis:26379"
          {{- else if .Values.redis.enabled }}
          value: "{{ .Release.Name }}-redis-master:6379"
          {{- else }}
          value: {{ .Values.cache.addrs | default "localhost:6379" | quote }}
          {{- end}}
        - name: REDIS_MASTER_NAME
          {{- if and .Values.redis.enabled .Values.redis.sentinel.enabled }}
          value: {{ .Values.redis.sentinel.masterSet | quote }}
          {{- else }}
          value: {{ .Values.cache.masterName | default "" | quote }}
          {{- end }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.redis.enabled }}
              name: {{ .Release.Name }}-redis
              key: redis-password
              {{- else }}
              name: {{ .Release.Name }}-secret
              key: REDIS_PASSWORD
              {{- end }}
        - name: CACHE_TTL
          value: {{ .Values.cache.ttl | default "24h" | quote }}
        - name: DATABASE_TTL
          value: {{ .Values.database.ttl | default "336h" | quote }}

        - name: PG_PASSWORD
          {{- if .Values.postgresql.enabled }}
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgres-app
              key: password 
          {{- else }}
          value: ""
          {{- end }}

        - name: CONNECTION_STRING
          {{- if and .Values.postgresql.enabled .Values.postgresql.pooler.enabled }}
          value: "postgres://{{ .Values.postgresql.username }}:$(PG_PASSWORD)@{{ .Release.Name }}-postgres-pooler:5432/{{ .Values.postgresql.database }}?sslmode=disable"
          {{- else if .Values.postgresql.enabled }}
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgres-app
              key: uri
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: CONNECTION_STRING
          {{- end }}
        - name: MAX_CONNS
          value: {{ .Values.database.maxConns | default "25" | quote }}
        - name: MIN_CONNS
          value: {{ .Values.database.minConns | default "5" | quote }}
        - name: MAX_CONN_LIFETIME
          value: {{ .Values.database.maxConnLifetime | default "1h" | quote }}
        - name: MAX_CONN_IDLETIME
          value: {{ .Values.database.maxConnIdletime | default "30m" | quote }}
        - name: HEALTH_CHECK_PERIOD
          value: {{ .Values.database.healthCheckPeriod | default "1m" | quote }}
        - name: CONNECTION_TIMEOUT
          value: {{ .Values.database.connectionTimeout | default "5s" | quote }}

        - name: ENABLE_TRACES
          value: {{ .Values.tracer.enabled | default false | quote }}
        - name: TRACER_RATIO
          value: {{ .Values.tracer.ratio | default "1" | quote }}
        - name: COLLECTOR_ADDR
          value: {{ .Values.tracer.addr | quote }}

        ports:
        - containerPort: {{ .Values.port | default 8080 }}
          name: api

        resources:
          {{- toYaml .Values.resources | nindent 10}}
        
        livenessProbe:
          httpGet:
            path: /healthz
            port: api
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: api
          initialDelaySeconds: 5
          periodSeconds: 10
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532 
          capabilities:
            drop:
              - ALL