- name: Install base packages
  ansible.builtin.apt:
    name: "{{ common_base_packages }}"
    state: present
    update_cache: true

- name: Install Helm
  ansible.builtin.include_tasks: helm.yaml

- name: Ensure iscsid service is enabled and running
  ansible.builtin.systemd:
    name: iscsid
    enabled: true
    state: started