apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Zapi-web/url-shortener
    targetRevision: main
    path: deploy/app
  destination:
    server: https://kubernetes.default.svc
    namespace: url-shortener 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    ignoreDifferences:
    - group: operator.victoriametrics.com
      kind: VMPodScrape
      jsonPointers:
        - /metadata
        - /spec
    - group: operator.victoriametrics.com
      kind: VMServiceScrape
      jsonPointers:
        - /metadata
        - /spec
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /spec/monitoring/customQueriesConfigMap
        - /spec/resources/limits/cpu
        - /spec/resources/requests/cpu