name: Helm Test and Push

on:
  workflow_call:

permissions: {}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
        
      - name: Set up Helm
        uses: azure/setup-helm@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          check-latest: true
      
      - name: Build chart dependencies
        run: helm dependency build deploy/app

      - name: Lint Helm Chart
        run: helm lint deploy/app

      - name: Dry-run template render
        run: helm template test-release deploy/app > /dev/null
  push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    needs: lint-test
    steps:
      - uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v5

      - name: Login to Github Packages
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Dependencies
        run: helm dependency build deploy/app

      - name: Package and Push Helm Chart
        run: |
          CHART_DIR="deploy/app"
          
          CHART_VERSION=$(yq '.version' $CHART_DIR/Chart.yaml)
          CHART_NAME=$(yq '.name' $CHART_DIR/Chart.yaml)

          REGISTRY_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm package $CHART_DIR

          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/${REGISTRY_OWNER}/charts