name: Main Pipeline

on:
    push:
        branches: [ main ]
        paths-ignore:
            - README.md
            - LICENSE
    pull_request:
        branches: [ main ]
        paths-ignore:
            - README.md
            - LICENSE

jobs:
    go-tests:
        uses: ./.github/workflows/go.yaml
    docker-registry-push:
        uses: ./.github/workflows/docker.yaml
        needs: go-tests
        if: github.event_name == 'push'
        secrets: inherit
        permissions:
            contents: read
            packages: write